//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpiderClueEntities : DbContext
    {
        public SpiderClueEntities()
            : base("name=SpiderClueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accessAccount> AccessAccounts { get; set; }
        public virtual DbSet<article> Articles { get; set; }
        public virtual DbSet<friendList> Friends { get; set; }
        public virtual DbSet<gamer> Gamers { get; set; }
        public virtual DbSet<guessPlayer> GuessPlayers { get; set; }
        public virtual DbSet<inventory> Inventories { get; set; }
        public virtual DbSet<match> Matches { get; set; }
        public virtual DbSet<matchResult> matchResults { get; set; }
        public virtual DbSet<report> Reports { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
